HtmlName = 'sample.html';               % the name of the current page
pageTitles = {'Page1','Page2','Page3'}; % other page links to add
pageLinks = {'#','#','#'};              
curpageTitle = 'Images';                
linkTitle = 'sample';                   % a link to the current page
pageDescription = 'This is an automatically-generated HTLM image gallery';
imDir = 'imdir/';                       % a directory of files to link thumbnails to
thumbDir = 'imdir/';                    % a directory of thumbnails (can be the same)
extType1 = 'jpg';                       % extention of files in the imdir (note: can be other HTML pages)
extType2 = 'jpg';                       % extention of files in thumbdir (should be images of some sort)
websiteName = 'Sample Images';
%%
% ------ A FEW NOTES ------
% If '\' occurs in HTML, put '\\' in MATLAB
% If single quotes occur in HTML, put '' (2 single quotes) in MATLAB
% -------------------------

% check that directories provided exist 
if ~exist(imDir,'dir'), error('%s does not exist',imDir); end
if ~exist(thumbDir,'dir'), error('%s does not exist',thumbDir); end

% check that the number of thumbnails matches the number of images
% to ensure a correspondence, images and thumbnails should appear in the
% same order in the corresponding directories
allims = dir(sprintf('%s*.%s',imDir,extType1)); 
allthumbs = dir(sprintf('%s*.%s',thumbDir,extType2)); 
if length(allims) ~= length(allthumbs)
    error('Number of thumbnails does not match number of images.')
end

nims = length(allims);

% open HTML page to write to
fp = fopen(HtmlName,'wt');

% -------- HTML HEAD -------- 
fprintf(fp,'<!DOCTYPE html>\n');
fprintf(fp,'<html>\n');
fprintf(fp,'<head>\n');
fprintf(fp,'<title>%s</title>\n',websiteName);
fprintf(fp,[...
'<meta charset="UTF-8">\n',...
'<meta name="description" content="">\n',...
'<meta name="keywords" content="">\n',...
'<meta name="viewport" content="width=device-width,initial-scale=1">\n',...
'<link rel="stylesheet" href="css/style.css">\n',...
'<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>\n',...
'<script>window.jQuery || document.write(''<script src="js/jquery.js"><\\/script>'')</script>\n',...
'<script src="js/scripts.js"></script>\n',...
'</head>\n',...
'<body>\n']);

% -------- HTML PAGE LINKS -------- 
fprintf(fp,[...
'<div id="fixedtop" class="clearfix">\n',...
'%s<div id="headercont" class="clearfix">\n',...
'%s<div id="headerright">\n',...
'%s<div class="menu">\n',...
'%s<ul>\n'],...
repmat(' ',1,4),repmat(' ',1,4*2),repmat(' ',1,4*3),repmat(' ',1,4*4));

fprintf(fp,'%s<li class="active"><a title="%s" href="%s">%s</a></li>\n',...
        repmat(' ',1,4*5),curpageTitle,HtmlName,linkTitle);

for i = 1:length(pageTitles)
   
   fprintf(fp,'%s<li><a title="" href="%s">%s</a></li>\n',...
           repmat(' ',1,4*5),pageLinks{i},pageTitles{i});
    
end

fprintf(fp,'%s</ul>\n%s</div>\n%s</div>\n%s</div>\n</div>\n',...
        repmat(' ',1,4*4),repmat(' ',1,4*3),repmat(' ',1,4*2),repmat(' ',1,4*1));

    
% -------- MAIN CONTENT -------- 
fprintf(fp,[...
'<div id="maincont" class="clearfix">\n',...
'%s<div id="main">\n',...
'%s<h1>%s</h1>\n',...
'%s<p>%s</p>\n',...
'%s<hr />\n',...
'%s<div id="portfoliocont" class="clearfix">\n',...
'%s<ul>\n'],repmat(' ',1,4),repmat(' ',1,4*2),'',repmat(' ',1,4*2),'',...
repmat(' ',1,4*2),repmat(' ',1,4*2),repmat(' ',1,4*3));

for i = 1:nims
    fprintf(fp,['%s<li><a title="" href="%s"><img alt="" src="%s" />',...
                '<div class="overlay link"></div></a></li>\n'],...
            repmat(' ',1,4*4),...
            fullfile(imDir,allims(i).name),...
            fullfile(thumbDir,allthumbs(i).name));    
end

fprintf(fp,'%s</ul>\n%s</div>\n%s<hr />\n%s</div>\n',...
        repmat(' ',1,4*3),repmat(' ',1,4*2),repmat(' ',1,4*2),repmat(' ',1,4));
            
fprintf(fp,[...
'%s<div id="footercont" class="clearfix">\n',...
'%s<p>%s &copy; 2012 - Free Website Template by ',...
'<a title="derby website design" href="http://www.derby-webdesign.co.uk/" ',...
'rel="external">Derby Web Design</a></p>\n',...
'%s</div>\n</div>\n'],...
repmat(' ',1,4),repmat(' ',1,4*2),websiteName,repmat(' ',1,4));

% -------- HTML END -------- 
fprintf(fp,'</body>\n</html>');
fclose(fp);
